/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as TestImport } from './routes/~test'
import { Route as DashboardAuthenticatedImport } from './routes/~dashboard/~_authenticated'
import { Route as landingPageIndexImport } from './routes/~(landing-page)/~index'
import { Route as authLoginIndexImport } from './routes/~(auth)/~login.index'
import { Route as DashboardAuthenticatedIndexImport } from './routes/~dashboard/~_authenticated/~index'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAuthenticatedRoute = DashboardAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => DashboardRoute,
} as any)

const landingPageIndexRoute = landingPageIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAuthenticatedIndexRoute =
  DashboardAuthenticatedIndexImport.update({
    path: '/',
    getParentRoute: () => DashboardAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/(landing-page)/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingPageIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_authenticated': {
      id: '/dashboard/_authenticated'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAuthenticatedImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_authenticated/': {
      id: '/dashboard/_authenticated/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardAuthenticatedIndexImport
      parentRoute: typeof DashboardAuthenticatedImport
    }
    '/(auth)/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DashboardAuthenticatedRouteChildren {
  DashboardAuthenticatedIndexRoute: typeof DashboardAuthenticatedIndexRoute
}

const DashboardAuthenticatedRouteChildren: DashboardAuthenticatedRouteChildren =
  {
    DashboardAuthenticatedIndexRoute: DashboardAuthenticatedIndexRoute,
  }

const DashboardAuthenticatedRouteWithChildren =
  DashboardAuthenticatedRoute._addFileChildren(
    DashboardAuthenticatedRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAuthenticatedRoute: typeof DashboardAuthenticatedRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuthenticatedRoute: DashboardAuthenticatedRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/test': typeof TestRoute
  '/': typeof landingPageIndexRoute
  '/dashboard': typeof DashboardAuthenticatedRouteWithChildren
  '/dashboard/': typeof DashboardAuthenticatedIndexRoute
  '/login': typeof authLoginIndexRoute
}

export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/': typeof landingPageIndexRoute
  '/dashboard': typeof DashboardAuthenticatedIndexRoute
  '/login': typeof authLoginIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/test': typeof TestRoute
  '/': typeof landingPageIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_authenticated': typeof DashboardAuthenticatedRouteWithChildren
  '/dashboard/_authenticated/': typeof DashboardAuthenticatedIndexRoute
  '/login/': typeof authLoginIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/test' | '/' | '/dashboard' | '/dashboard/' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/test' | '/' | '/dashboard' | '/login'
  id:
    | '__root__'
    | '/test'
    | '/'
    | '/dashboard'
    | '/dashboard/_authenticated'
    | '/dashboard/_authenticated/'
    | '/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  TestRoute: typeof TestRoute
  landingPageIndexRoute: typeof landingPageIndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  TestRoute: TestRoute,
  landingPageIndexRoute: landingPageIndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/test",
        "/",
        "/dashboard",
        "/login/"
      ]
    },
    "/test": {
      "filePath": "~test.tsx"
    },
    "/": {
      "filePath": "~(landing-page)/~index.tsx"
    },
    "/dashboard": {
      "filePath": "~dashboard",
      "children": [
        "/dashboard/_authenticated"
      ]
    },
    "/dashboard/_authenticated": {
      "filePath": "~dashboard/~_authenticated.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_authenticated/"
      ]
    },
    "/dashboard/_authenticated/": {
      "filePath": "~dashboard/~_authenticated/~index.tsx",
      "parent": "/dashboard/_authenticated"
    },
    "/login/": {
      "filePath": "~(auth)/~login.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
